# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_thing_notes'),
        ('persons', '0002_auto_20170515_1200'),
        ('statements', '0002_mark_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(verbose_name='Дата находки/пропажи: ')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес пропажи/находки: ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.Country')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.Mark')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.Status')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Thing')),
            ],
        ),
    ]
