# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_auto_20170515_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Тема: ')),
                ('letter', models.TextField(default=None, verbose_name='Текст: ')),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_from', to='persons.Person', verbose_name='От кого: ')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Кому: ')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
