# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Вещи',
                'verbose_name': 'Вещь',
            },
        ),
        migrations.AlterModelOptions(
            name='thingcategory',
            options={'verbose_name': 'Категория вещей', 'verbose_name_plural': 'Категории вещей'},
        ),
        migrations.AddField(
            model_name='thing',
            name='thing_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.ThingCategory'),
        ),
    ]
