# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20170515_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='notes',
            field=models.TextField(blank=True, default=None),
        ),
    ]
